create table
  public.transactions (
    id bigint generated by default as identity,
    title character varying not null default ''::character varying,
    description character varying null default ''::character varying,
    amount numeric not null,
    date date not null,
    constraint Transactions_pkey primary key (id),
    constraint Transactions_id_key unique (id)
  ) tablespace pg_default;
